### ISSUE TITLE
'websocket' example appears to be out of date for client.rs

### ISSUE THREAD

**Issue by mcarlin** [actix/examples#123]
I might be missing something but the client.rs doesn't appear to up to date with the latest APIs.  If I uncomment the client binary in the `Cargo.toml`, I see the following errors:
```
cargo build
   Compiling websocket v0.1.0 (/Users/mike/code/examples/websocket)
error[E0432]: unresolved imports `actix_web::client::ClientWriter`, `actix_web::client::Message`, `actix_web::client::ProtocolError`
 --> websocket/src/client.rs:6:33
  |
6 | use actix_web::client::{Client, ClientWriter, Message, ProtocolError};
  |                                 ^^^^^^^^^^^^  ^^^^^^^  ^^^^^^^^^^^^^ no `ProtocolError` in `client`
  |                                 |             |
  |                                 |             no `Message` in `client`
  |                                 no `ClientWriter` in `client`
  |                                 help: a similar name exists in the module: `ClientBuilder`

warning: unused import: `Message`
 --> websocket/src/client.rs:6:47
  |
6 | use actix_web::client::{Client, ClientWriter, Message, ProtocolError};
  |                                               ^^^^^^^
  |
  = note: #[warn(unused_imports)] on by default

error[E0191]: the value of the associated type `Result` (from the trait `_impl_act_clientcommand::actix::Message`) must be specified
  --> websocket/src/client.rs:87:20
   |
87 | impl StreamHandler<Message, ProtocolError> for ChatClient {
   |                    ^^^^^^^ associated type `Result` must be specified

error[E0191]: the value of the associated type `Result` (from the trait `_impl_act_clientcommand::actix::Message`) must be specified
  --> websocket/src/client.rs:88:31
   |
88 |     fn handle(&mut self, msg: Message, ctx: &mut Context<Self>) {
   |                               ^^^^^^^ associated type `Result` must be specified

error: aborting due to 3 previous errors

Some errors occurred: E0191, E0432.
For more information about an error, try `rustc --explain E0191`.
error: Could not compile `websocket`.

```

**Comment by jesskfullwood** [comment]
As I mentioned when this was brought up in the [main repo](https://github.com/actix/actix-web/issues/829), I have tried to fix this, and I think doing so uncovers some weaknesses in the API. In particular:

* It is unclear when one is supposed to use a `Frame` vs a `Message`. It looks like `Frame` is for receiving messages and `Message` is for sending them, which makes sense except that the websocket actor `StreamHandler` [accepts a `Message`, not a `Frame`](https://github.com/actix/actix-web/blob/5826f39dbe15791a171fa8ea15d675e98803297a/actix-web-actors/src/ws.rs#L29-L33) 

* Unclear when/whether a `WebsocketContext` actor is useful. It seems that `WebsocketContext` is supposed to be used by servers, not clients, but since a websocket is full-duplex this does not seem like a useful distinction

**Comment by jesskfullwood** [comment]
I had another go at this today and again failed to get it working - too much type-tetris. I really hope someone can take a look at this pre-`1.0`.

**Comment by guoli-lyu** [comment]
Hey, I have figure out a working example and have made a PR. Comments are welcomed.

**Comment by fafhrd91** [comment]
fix is merged
