### ISSUE TITLE
[Example Request] Download Counter

### ISSUE THREAD

**Issue by Th3Whit3Wolf** [actix/examples#184]
I am making this request because I have no idea about to go about it, but it would be cool to see an example of a very simple file server with a download counter.

**Comment by bitemyapp** [comment]
Depends on how you want to store the state and what your purpose for the example is. I'm a little disinclined against demonstrating in-memory state in the app server because almost nobody should be doing this for any purpose. Something using PostgreSQL or Redis would fit the most common cases I believe.

**Comment by Th3Whit3Wolf** [comment]
Could this also be done with an embed key value store database like [sled](https://github.com/spacejam/sled)? What would the best way be to extract that information from the database?

**Comment by Th3Whit3Wolf** [comment]
For sure. How would you go about it with PostgreSQL?

**Comment by bevanhunt** [comment]
@Th3Whit3Wolf I took up your example challenge and here it is https://github.com/apibillme/download-counter-example (Actix Web, SSE, and Sled)

**Comment by Th3Whit3Wolf** [comment]
@bevanhunt thank you! It looks exactly like what I was looking for.
