### ISSUE TITLE
Revive some examples

### ISSUE THREAD

**Issue by JohnTitor** [actix/examples#292]
Currently, they're excluded from the workspace:
- [ ] `udp-echo`
- [x] `websocket-chat-broker`

We should bump up the dependencies and revive the examples.

**Comment by Jonathas-Conceicao** [comment]
I have tackled the `udp-echo` example a while back, progress can be seen in a [my fork](https://github.com/Jonathas-Conceicao/examples/tree/topic/update_udp_echo).

The problem with this one is that it depends on usage of actor's reference on a future spawned into the context which I wasn't able to clone at first. I've fixed with a unsafe deref, but didn't wanna open a PR for it like that. I'll look some more into it to see if there's a way to redesign it without the lifetime dependency for the `Future`.

**Comment by robjtede** [comment]
I'll have a crack at websocket-chat-broker.

**Comment by robjtede** [comment]
Seems udp-echo will be checked off soon too with #336. Was it a library limitation before when you had a go @Jonathas-Conceicao?

**Comment by Jonathas-Conceicao** [comment]
I was unable to port it using types from tokio and futures crates. I guess it slipped my mind that `actix::io::SInkWrite` could be used to solve the ownership problem I had there.

**Comment by alvardes** [comment]
@Jonathas-Conceicao I guess I had the same problem. I found out about `SinkWrite` from the websocket example :confused:. Honestly it is not very discoverable from just the docs itself.
