### ISSUE TITLE
Add example for unit tests

### ISSUE THREAD

**Issue by leplatrem** [actix/examples#73]
It would extremely useful to see a well-structured test suite, where requests are forged and sent to a test server in order to assert responses content.

Does anyone know an existing project that does that well out there? I would be happy to contribute a small example if there's a model I can be inspired by ;)

**Comment by augustocdias** [comment]
I have one of a project I'm working for my company. 
https://github.com/augustocdias/rustbier/
You can check the `tests` directory
In my perspective, the problem is the external dependencies... (which the actual app will be one as well).
It might not be the best example that you're expecting because my API basically returns images and not HTML/JSON responses, but you can have an idea on how it works.
Bear in mind that I haven't adapted the code to be in github yet, because it was originally meant to be only in our internal gitlab. To make it work, you'll have to adapt some files. Basically you'll have to change the docker tag names in the `Makefile`, the `Dockerfile` to point to the base image you just built instead the one pointing to our internal registry (I made 2 images, because opencv and imagemagick take too long to compile), the `docker-compose` to point to the official `minio` (our have a embedded client packaged) image and the `setup.sh` to add the images to the `minio` container.

**Comment by leizzer** [comment]
You can use any 3rd party tool you like or create a client that assert the response. (some of the [examples](https://github.com/actix/examples) have python clients to test the examples)

**Comment by robjtede** [comment]
many examples have tests now: https://github.com/actix/examples/search?q=test
